### ISSUE TITLE
0.2.3 not on cdnjs

### ISSUE THREAD

**Issue by lillereven** [XavierBoubert/ractive-require#2]
the CDN has 0.2.0

**Comment by XavierBoubert** [comment]
Yes I know. It's in validation from more than 1 month ago on cdnjs...

**Comment by XavierBoubert** [comment]
Yes I know. It's in validation from more than 1 month ago on cdnjs...

**Comment by XavierBoubert** [comment]
The last version (0.2.4) is updated on the CDN: https://cdnjs.com/libraries/ractive-require
