### ISSUE TITLE
Is it possible to load "vendor" javascript libraries on demand?

### ISSUE THREAD

**Issue by pangard** [XavierBoubert/ractive-require#4]
Hello. I would like to know the preferred way to load external libraries. So I can load on demand ractive components that are self-contained, but what if they need a rich text editor, graphing library, table editing plugin, etcetera. This is heavy stuff I don't want to load if the user does not need it. Currently I'm using $.getScript.

Not sure if this is a question or a feature request ;-)?

**Comment by XavierBoubert** [comment]
Yes you can require an asset file (CSS or JS) diectly: http://ractive-require.codecorico.com/#require-a-file-directly

In my use cases, I use [Page.js](https://visionmedia.github.io/page.js). In the route controller I use:

``` javascript
// Enter in the /my-feature url
page('/my-feature', function() {

  // Require every vendor libraries
  // (It doesn't reload a library already injected)
  require('/vendor/jquery.min.js')
    .then(function() {
      return require('/vendor/md5.js');
    })
    .then(function() {
      return require('/vendor/async.js');
    })
    .then(function() {

      // Now I use my main view and I require the <rv-require ondemand="my-feature">
      return Page.require('my-feature');
    })
    .then(function() {

      // The my-feature view with its children are rendered
      console.log('complete');
    });

});
```

**Comment by pangard** [comment]
Thanks!
